-- V1__init_schema.sql
-- Generated by 9raya Spring Generator
-- Database Migration: Initial Schema

<#list tables as table>
<#if !table.joinTable>
CREATE TABLE ${table.name} (
<#assign colIndex = 0>
<#list table.columns as col>
<#assign colIndex = colIndex + 1>
    ${col.name} ${col.type}<#if col.primaryKey> PRIMARY KEY</#if><#if col.autoIncrement> AUTO_INCREMENT</#if><#if !col.nullable> NOT NULL</#if><#if col.unique> UNIQUE</#if><#if colIndex < table.columns?size>,</#if>
</#list>
);

</#if>
</#list>
-- Join Tables
<#list tables as table>
<#if table.joinTable>
CREATE TABLE ${table.name} (
<#assign colIndex = 0>
<#list table.columns as col>
<#assign colIndex = colIndex + 1>
    ${col.name} ${col.type}<#if !col.nullable> NOT NULL</#if><#if colIndex < table.columns?size>,</#if>
</#list>
);

</#if>
</#list>
-- Foreign Key Constraints
<#list tables as table>
<#list table.columns as col>
<#if col.foreignKey>
ALTER TABLE ${table.name} ADD CONSTRAINT fk_${table.name}_${col.name}
    FOREIGN KEY (${col.name}) REFERENCES ${col.referencedTable}(${col.referencedColumn});

</#if>
</#list>
</#list>
